"""Seed a demo Acme Corp workspace with sample documents."""
import uuid
from datetime import datetime, timezone

from auth_utils import hash_password
from doc_parser import chunk_text

DEMO_COMPANY = "Acme Corp"
DEMO_ADMIN_EMAIL = "admin@acme.com"
DEMO_ADMIN_PASSWORD = "Admin@123"
DEMO_EMPLOYEE_EMAIL = "employee@acme.com"
DEMO_EMPLOYEE_PASSWORD = "Employee@123"

SAMPLE_DOCS = [
    {
        "name": "HR Policy Handbook.txt",
        "department": "HR",
        "content": """ACME CORP - HR POLICY HANDBOOK

LEAVE POLICY
- Annual paid leave: 18 days per year for all full-time employees.
- Sick leave: 12 days per year, doctor's certificate required after 3 consecutive days.
- Maternity leave: 26 weeks of fully-paid leave.
- Paternity leave: 2 weeks of fully-paid leave.
- Leave applications must be submitted via the HR portal at least 5 working days in advance, except for emergencies.

WORK FROM HOME POLICY
- Employees are allowed to work from home up to 2 days per week.
- Prior approval from the line manager is required.
- A stable internet connection and quiet workspace are mandatory.

EXPENSE & REIMBURSEMENT POLICY
- Expenses under INR 5,000 can be self-approved by the employee.
- Expenses above INR 5,000 require approval from the line manager.
- Expenses above INR 50,000 require approval from the Finance Head.
- All expense claims must be submitted within 7 days with valid receipts.

PROBATION & ONBOARDING
- All new employees go through a 6-month probation period.
- Onboarding is completed within the first week and includes IT setup, HR orientation, and team introductions.

CODE OF CONDUCT
- Office hours: 9:30 AM to 6:30 PM, Monday to Friday.
- Dress code: smart casual; business formal during client meetings.
- Zero tolerance for harassment of any kind.
""",
    },
    {
        "name": "Sales SOP.txt",
        "department": "Sales",
        "content": """ACME CORP - SALES STANDARD OPERATING PROCEDURE

CRM TOOL
- The official CRM used by Acme Corp is Salesforce.
- All leads, opportunities and customer interactions must be logged in Salesforce within 24 hours.

QUOTATION PROCESS
1. Create a new opportunity in Salesforce.
2. Use the standard Quote Template v3.2 (available in the Sales Drive).
3. Quotation must include itemised pricing, taxes and validity (default 15 days).
4. All quotations above INR 10 lakh require Sales Manager approval before sending to client.

DISCOUNT POLICY
- Maximum discount allowed without approval: 10%.
- Discounts between 10% and 20% require Sales Director approval.
- Any discount above 20% requires CEO approval (no exceptions).

CLIENT ONBOARDING
- Send welcome email within 24 hours of contract signing.
- Schedule kickoff call within 5 working days.
- Hand over to Customer Success team within 14 days.

LEAD QUALIFICATION
- Use the BANT framework: Budget, Authority, Need, Timeline.
- Only qualified leads are passed to Account Executives.
""",
    },
    {
        "name": "Finance Process.txt",
        "department": "Finance",
        "content": """ACME CORP - FINANCE PROCESS DOCUMENT

INVOICE GENERATION
- Invoices are generated by the Finance Operations team within 2 working days of milestone completion.
- All invoices must include GSTIN, PAN, HSN/SAC codes and a unique invoice number.
- Invoices are sent via email and copied to the client's accounts payable team.

PAYMENT TERMS
- Standard payment terms: Net 30 (30 days from invoice date).
- Premium clients may have Net 45 terms with CFO approval.
- Late payments incur 1.5% interest per month after a 15-day grace period.

GST FILING PROCESS
- GSTR-1 filed by the 11th of every month.
- GSTR-3B filed by the 20th of every month.
- All input tax credits reconciled monthly against GSTR-2A/2B.

EXPENSE APPROVAL HIERARCHY
- Below INR 5,000: self-approval.
- INR 5,000 to INR 50,000: line manager approval.
- Above INR 50,000: Finance Head approval.
- Above INR 5 lakh: CFO approval.

REIMBURSEMENT
- All reimbursement claims must be submitted within 7 days with valid receipts.
- Reimbursements are processed in the next payroll cycle.
- Use the official reimbursement form available on the HR portal.
""",
    },
]


async def seed_demo_company(db) -> dict:
    """Create demo company if it doesn't exist. Returns status info."""
    existing = await db.companies.find_one({"name": DEMO_COMPANY})
    if existing:
        return {"seeded": False, "reason": "demo already exists"}

    now = datetime.now(timezone.utc).isoformat()
    company_id = str(uuid.uuid4())
    admin_id = str(uuid.uuid4())
    employee_id = str(uuid.uuid4())

    await db.companies.insert_one({
        "id": company_id,
        "name": DEMO_COMPANY,
        "created_at": now,
    })

    await db.users.insert_many([
        {
            "id": admin_id,
            "company_id": company_id,
            "email": DEMO_ADMIN_EMAIL,
            "name": "Acme Admin",
            "password_hash": hash_password(DEMO_ADMIN_PASSWORD),
            "role": "admin",
            "created_at": now,
        },
        {
            "id": employee_id,
            "company_id": company_id,
            "email": DEMO_EMPLOYEE_EMAIL,
            "name": "Acme Employee",
            "password_hash": hash_password(DEMO_EMPLOYEE_PASSWORD),
            "role": "employee",
            "created_at": now,
        },
    ])

    for d in SAMPLE_DOCS:
        doc_id = str(uuid.uuid4())
        chunks = chunk_text(d["content"])
        await db.documents.insert_one({
            "id": doc_id,
            "company_id": company_id,
            "name": d["name"],
            "department": d["department"],
            "content": d["content"],
            "chunks": chunks,
            "size_bytes": len(d["content"].encode("utf-8")),
            "uploaded_by": admin_id,
            "created_at": now,
        })

    return {
        "seeded": True,
        "company_id": company_id,
        "admin_email": DEMO_ADMIN_EMAIL,
        "employee_email": DEMO_EMPLOYEE_EMAIL,
    }
